# Meaning of params please see at https://github.com/leoleovich/grafsy/blob/master/README.md
clientSendInterval = 10

maxMetrics = 5000

graphiteAddr = "127.0.0.1:2003"

localBind = "127.0.0.1:3002"

log = "/var/log/grafsy/grafsy.log"

metricDir = "/tmp/grafsy"

retryFile = "/tmp/grafsy-retry"

sumPrefix = "SUM."

sumInterval = 60

grafsyPrefix = "servers"
grafsySuffix = "software"

allowedMetrics = "^(powerline|backend|corporatesystems|carbon|games|hwlbs|powerline|servers|switches|network|test|cdn|SUM)\\.[-a-zA-Z0-9_]+\\.[-a-zA-Z0-9_\\(\\)\\.\\:\\/\\,\\{\\}=\\+]+(\\s)[-0-9\\.eE+]+(\\s)[0-9]{10}"